#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Wait for mount
while ! mount | grep "$RCLONE_MOUNT_DIR"; do
    echo "Waiting for mount..."
    sleep 5
done

# The original image's entrypoint
if [[ -n $WALLET_FEATURES ]]; then
    exec /entrypoint "--operator.wallet-features=$WALLET_FEATURES"
else
    exec /entrypoint
fi