#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -e

# Wait for mount
while ! mount | grep "$RCLONE_MOUNT_DIR"; do
    echo "Waiting for mount..."
    sleep 5
done

cd /app

# The original image's entrypoint
if [[ -n $WALLET_FEATURES ]]; then
    /entrypoint "--operator.wallet-features=$WALLET_FEATURES"
else
    /entrypoint
fi

if [[ -n $SETUP ]]; then
    echo "Waiting 60s after setup..."
    sleep 60
fi

cd -
