#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -e

umount /app/config || true
mkdir -p /app/config

exec rclone mount -v \
    --config="$RCLONE_CONFIG" \
    --vfs-read-chunk-size 100M \
    --cache-dir "${RCLONE_MOUNT_CACHE_DIR}" \
    --vfs-cache-mode full \
    --vfs-cache-poll-interval 1h0m0s \
    "$MOUNT_SOURCE" \
    /app/config
