#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umount "${RCLONE_MOUNT_TARGET}"
mkdir -p "${RCLONE_MOUNT_TARGET}"
exec rclone mount -v \
    --config="$RCLONE_CONFIG" \
    --vfs-read-chunk-size 100M \
    --cache-dir "${RCLONE_MOUNT_CACHE_DIR}" \
    --vfs-cache-mode full \
    --vfs-cache-poll-interval 1h0m0s \
    "${RCLONE_MOUNT_DIR}" \
    "${RCLONE_MOUNT_TARGET}"
